// planes.js - Datos de los planes de entrenamiento
const planes = {
    "30min":[
        [["Lunes","20 min caminata rápida + 3x10 sentadillas"],["Martes","5x1 min trote suave + 2 min caminando"],["Miércoles","Descanso"],["Jueves","6x1 min trote + 1.5 min caminando"],["Viernes","15 min caminata rápida con cambios de ritmo"],["Sábado","Descanso"],["Domingo","4x1.5 min trote + 2 min caminando"]],
        [["Lunes","20 min caminata rápida + 3x12 sentadillas + 10 zancadas"],["Martes","5x2 min trote suave + 1.5 min caminando"],["Miércoles","Descanso"],["Jueves","6x2 min trote + 1 min caminando"],["Viernes","18 min alternando 2 min trote + 1 min caminar"],["Sábado","Descanso"],["Domingo","4x2.5 min trote + 1.5 min caminando"]],
        [["Lunes","15 min caminata + 3x15 sentadillas + 12 zancadas"],["Martes","4x3 min trote + 1 min caminando"],["Miércoles","Descanso"],["Jueves","6x2 min trote con 30 seg más rápido al final + 1 min caminar"],["Viernes","10 min trote continuo suave"],["Sábado","Descanso"],["Domingo","3x5 min trote + 2 min caminando"]],
        [["Lunes","15 min caminata rápida + 4x12 sentadillas + 3x10 zancadas"],["Martes","3x5 min trote + 1 min caminando"],["Miércoles","Descanso"],["Jueves","5x3 min trote con último min más rápido + 1 min caminar"],["Viernes","12 min trote continuo suave"],["Sábado","Descanso"],["Domingo","2x8 min trote + 2 min caminando"]],
        [["Lunes","10 min caminata + 4x15 sentadillas + 3x12 zancadas"],["Martes","15 min trote continuo suave"],["Miércoles","Descanso"],["Jueves","4x3 min ritmo medio + 1 min trote suave"],["Viernes","12 min trote + 3 min más rápido"],["Sábado","Descanso"],["Domingo","18 min trote continuo a ritmo cómodo"]],
        [["Lunes","10 min caminata + 4x15 sentadillas + 4x12 zancadas"],["Martes","18 min trote continuo suave"],["Miércoles","Descanso"],["Jueves","5x3 min ritmo medio + 1 min trote suave"],["Viernes","15 min trote + 3 min progresivo"],["Sábado","Descanso"],["Domingo","22 min trote continuo a ritmo cómodo"]],
        [["Lunes","10 min caminata + 4x15 sentadillas + 4x12 zancadas + 30 seg plancha"],["Martes","22 min trote continuo suave"],["Miércoles","Descanso"],["Jueves","4x4 min ritmo medio + 1 min trote suave"],["Viernes","18 min trote + 4 min progresivo"],["Sábado","Descanso"],["Domingo","25 min trote continuo a ritmo cómodo"]],
        [["Lunes","10 min caminata + 4x15 sentadillas + 4x12 zancadas + 45 seg plancha"],["Martes","25 min trote continuo suave"],["Miércoles","Descanso"],["Jueves","3x5 min ritmo medio + 1 min trote suave"],["Viernes","20 min trote + 5 min progresivo"],["Sábado","Descanso"],["Domingo","30 min trote continuo"]]
    ],
    "5k":[
        [["Lunes","Fuerza básica: 3x12 sentadillas + 10 zancadas + 20 seg plancha"],["Martes","2 km trote suave alternando con caminata"],["Miércoles","Descanso"],["Jueves","6x1 min trote + 1.5 min caminando"],["Viernes","2 km trote suave continuo"],["Sábado","Descanso"],["Domingo","2.5 km trote/caminata a ritmo cómodo"]],
        [["Lunes","Fuerza: 3x15 sentadillas + 12 zancadas + 30 seg plancha"],["Martes","2.5 km trote suave continuo"],["Miércoles","Descanso"],["Jueves","5x2 min trote + 1 min caminando"],["Viernes","2.5 km trote con últimos 500m más rápido"],["Sábado","Descanso"],["Domingo","3 km trote suave continuo"]],
        [["Lunes","Fuerza: 4x12 sentadillas + 3x10 zancadas + 30 seg plancha + skipping"],["Martes","3 km carrera suave continua"],["Miércoles","Descanso"],["Jueves","6x200m ritmo rápido + 200m trote suave"],["Viernes","3 km con último km a ritmo medio"],["Sábado","Descanso"],["Domingo","4 km carrera suave"]],
        [["Lunes","Fuerza: 4x15 sentadillas + 3x12 zancadas + 40 seg plancha + skipping"],["Martes","3.5 km carrera suave continua"],["Miércoles","Descanso"],["Jueves","5x400m ritmo fuerte + 400m trote suave"],["Viernes","3 km tempo a ritmo medio constante"],["Sábado","Descanso"],["Domingo","5 km carrera suave"]],
        [["Lunes","Fuerza: 4x15 sentadillas + 4x12 zancadas + 45 seg plancha"],["Martes","4 km carrera suave continua"],["Miércoles","Descanso"],["Jueves","4x600m a ritmo 5K + 400m trote suave"],["Viernes","4 km con 2 km centrales a ritmo 5K"],["Sábado","Descanso"],["Domingo","6 km carrera suave"]],
        [["Lunes","Fuerza: 4x15 sentadillas + 4x12 zancadas + 45 seg plancha + técnica carrera"],["Martes","4 km carrera suave"],["Miércoles","Descanso"],["Jueves","3x1000m a ritmo 5K + 500m trote suave"],["Viernes","5 km con 3 km centrales a ritmo 5K"],["Sábado","Descanso"],["Domingo","7 km carrera suave"]],
        [["Lunes","Fuerza ligera: 3x12 sentadillas + 3x10 zancadas + 30 seg plancha"],["Martes","4 km carrera suave"],["Miércoles","Descanso"],["Jueves","6x400m a ritmo 5K + 200m trote"],["Viernes","3 km suave + 2 km progresivo hasta ritmo 5K"],["Sábado","Descanso"],["Domingo","5 km simulacro a ritmo objetivo"]],
        [["Lunes","Activación: 15 min trote muy suave + movilidad articular"],["Martes","3 km carrera suave"],["Miércoles","Descanso"],["Jueves","4x200m ritmo rápido + trote suave (activación)"],["Viernes","2 km trote muy suave + estiramientos"],["Sábado","Descanso"],["Domingo","CARRERA 5K – ¡A darlo todo!"]]
    ],
    "fartlek":[
        [["Lunes","3 km suaves + 4x(30 seg ritmo alegre + 90 seg suave)"],["Martes","25 min trote cómodo + movilidad"],["Miércoles","Descanso"],["Jueves","3 km con 5 cambios de 1 min rápido + 2 min suave"],["Viernes","20 min carrera muy suave"],["Sábado","Descanso"],["Domingo","4 km progresivos con últimos 5 min algo más rápidos"]],
        [["Lunes","4 km suaves + 5x(45 seg ritmo alto + 90 seg suave)"],["Martes","30 min trote cómodo"],["Miércoles","Descanso"],["Jueves","4 km fartlek: 6x(1 min rápido + 2 min suave)"],["Viernes","25 min recuperación suave + técnica de carrera"],["Sábado","Descanso"],["Domingo","5 km controlados con 3 bloques de 2 min a ritmo medio"]],
        [["Lunes","4.5 km suaves + 6x(1 min rápido + 90 seg suave)"],["Martes","30 min trote cómodo"],["Miércoles","Descanso"],["Jueves","5 km fartlek: 5x(2 min ritmo fuerte + 2 min suave)"],["Viernes","25 min muy suaves + movilidad"],["Sábado","Descanso"],["Domingo","6 km continuos a ritmo cómodo"]],
        [["Lunes","5 km suaves + 6x(1 min rápido + 1 min suave)"],["Martes","35 min trote cómodo"],["Miércoles","Descanso"],["Jueves","5 km fartlek: 4x(3 min ritmo fuerte + 2 min suave)"],["Viernes","30 min recuperación + técnica"],["Sábado","Descanso"],["Domingo","6.5 km progresivos con final a ritmo medio"]],
        [["Lunes","5.5 km suaves + 8 cambios de 1 min rápido + 1 min suave"],["Martes","35 min trote cómodo"],["Miércoles","Descanso"],["Jueves","6 km fartlek: 5x(3 min fuerte + 90 seg suave)"],["Viernes","30 min muy suaves + movilidad"],["Sábado","Descanso"],["Domingo","7 km continuos con 10 min finales más alegres"]],
        [["Lunes","5 km suaves + 5x(2 min ritmo alto + 2 min suave)"],["Martes","30 min trote cómodo"],["Miércoles","Descanso"],["Jueves","6 km fartlek final: 4x(4 min ritmo fuerte + 2 min suave)"],["Viernes","25 min muy suaves + estiramientos"],["Sábado","Descanso"],["Domingo","7 km test controlado con cambios de ritmo sostenidos"]]
    ],
    "hiit":[
        [["Lunes","Fuerza explosiva: 3 rondas de 20s sentadilla con salto + 40s descanso x5"],["Martes","Cardio HIIT: 3 rondas de 20s sprint + 40s caminar x5"],["Miércoles","Descanso"],["Jueves","Circuito: 3 rondas (20s burpees + 20s skipping + 20s sentadillas) 40s descanso"],["Viernes","Core HIIT: 3 rondas de 20s mountain climbers + 20s plancha + 40s descanso"],["Sábado","Descanso"],["Domingo","HIIT largo: 4x1 min trote rápido + 1 min caminando"]],
        [["Lunes","Fuerza explosiva: 3 rondas de 20s salto zancada + 20s sentadilla salto + 40s desc x4"],["Martes","Cardio HIIT: 3 rondas de 20s sprint cuesta + 40s bajar caminando x5"],["Miércoles","Descanso"],["Jueves","Circuito: 3 rondas (20s burpees + 20s jumping jacks + 20s plancha) 40s desc"],["Viernes","Core HIIT: 3 rondas (20s mountain climbers + 20s plancha lateral + 20s bicicleta) 40s desc"],["Sábado","Descanso"],["Domingo","HIIT largo: 5x1 min trote rápido + 1 min caminando"]],
        [["Lunes","Fuerza explosiva: 3 rondas de 30s sentadilla salto + 30s zancada salto + 30s desc x4"],["Martes","Cardio HIIT: 3 rondas de 30s sprint + 30s trote suave x6"],["Miércoles","Descanso"],["Jueves","Circuito: 3 rondas (30s burpees + 30s skipping + 30s sentadillas + 30s plancha) 30s desc"],["Viernes","Core + plio: 3 rondas (30s mountain climbers + 30s saltos tijera + 30s plancha dinámica) 30s desc"],["Sábado","Descanso"],["Domingo","HIIT largo: 5x90 seg ritmo fuerte + 1 min caminando"]],
        [["Lunes","Fuerza explosiva: 3 rondas (30s sentadilla salto + 30s burpees + 30s zancada salto) 30s desc"],["Martes","Cardio HIIT: 4 rondas de 30s sprint + 30s trote suave x6"],["Miércoles","Descanso"],["Jueves","Circuito: 3 rondas (30s burpees + 30s jumping jacks + 30s sentadillas + 30s skipping + 30s plancha) 30s desc"],["Viernes","Core + plio: 3 rondas (30s mountain climbers + 30s rodillas al pecho + 30s salto estrella) 30s desc"],["Sábado","Descanso"],["Domingo","HIIT largo: 6x90 seg ritmo fuerte + 45 seg caminando"]],
        [["Lunes","Fuerza explosiva: 3 rondas (40s sentadilla salto + 40s burpees + 40s zancada salto) 20s desc"],["Martes","Tabata cardio: 4 rondas de 20s sprint máximo + 10s descanso x8"],["Miércoles","Descanso"],["Jueves","Circuito: 4 rondas (40s burpees + 40s skipping + 40s sentadilla salto + 40s plancha) 20s desc"],["Viernes","Core + plio: 4 rondas (40s mountain climbers + 40s plancha dinámica + 40s saltos laterales) 20s desc"],["Sábado","Descanso"],["Domingo","HIIT largo: 6x2 min ritmo fuerte + 45 seg trote suave"]],
        [["Lunes","Fuerza explosiva: 4 rondas (40s sentadilla salto + 40s burpees + 40s zancada explosiva) 20s desc"],["Martes","Tabata cardio: 4 rondas de 20s sprint máximo + 10s desc x8 (2 min pausa entre rondas)"],["Miércoles","Descanso"],["Jueves","Circuito: 4 rondas (40s burpees + 40s jumping jacks + 40s sentadilla salto + 40s skipping + 40s plancha) 20s desc"],["Viernes","Core intenso: 4 rondas (40s mountain climbers + 40s V-ups + 40s plancha lateral dinámica) 20s desc"],["Sábado","Descanso"],["Domingo","HIIT largo: 8x2 min ritmo fuerte + 30 seg trote suave"]],
        [["Lunes","Fuerza explosiva: 4 rondas (45s sentadilla salto + 45s burpees + 45s zancada salto) 15s desc"],["Martes","Tabata mixto: 4 rondas (20s burpee + 10s desc + 20s sprint + 10s desc) x4"],["Miércoles","Descanso"],["Jueves","Circuito: 4 rondas (45s burpees + 45s skipping + 45s sentadilla salto + 45s mountain climbers + 45s plancha) 15s desc"],["Viernes","Core + plio: 4 rondas (45s mountain climbers + 45s saltos estrella + 45s plancha dinámica + 45s tijeras) 15s desc"],["Sábado","Descanso"],["Domingo","HIIT largo: 8x2 min ritmo fuerte + 20 seg recuperación activa"]],
        [["Lunes","Fuerza explosiva: 4 rondas (45s sentadilla salto + 45s burpees + 45s zancada explosiva + 45s flexiones) 15s desc"],["Martes","Tabata final controlado: 4 rondas (20s ritmo alto + 10s desc) x8"],["Miércoles","Descanso"],["Jueves","Circuito completo: 4 rondas (45s burpees + 45s skipping + 45s sentadilla salto + 45s mountain climbers + 45s plancha + 45s jumping jacks) 15s desc"],["Viernes","Core final: 4 rondas (45s mountain climbers + 45s V-ups + 45s plancha dinámica + 45s rodillas al pecho) 15s desc"],["Sábado","Descanso"],["Domingo","HIIT evaluación: 8x1 min ritmo alto controlado + 45 seg descanso"]]
    ],
    "trail":[
        [["Lunes","Fuerza básica: 3x10 sentadillas + 3x10 zancadas + 20 min caminata en sendero"],["Martes","3 km trote suave en sendero llano"],["Miércoles","Descanso"],["Jueves","20 min alternando 2 min trote + 1 min caminar en sendero"],["Viernes","30 min caminata en sendero con desnivel suave"],["Sábado","Descanso"],["Domingo","5 km caminata/trote en sendero natural"]],
        [["Lunes","Fuerza: 3x12 sentadillas + 3x10 zancadas + 10 min escalones"],["Martes","4 km trote suave en sendero llano"],["Miércoles","Descanso"],["Jueves","25 min alternando 3 min trote + 1 min caminar en sendero"],["Viernes","35 min trote suave en sendero con cuestas cortas"],["Sábado","Descanso"],["Domingo","6 km trote suave en sendero natural"]],
        [["Lunes","Fuerza trail: 4x10 sentadillas + 4x10 zancadas + 15 min subida/bajada escalones"],["Martes","5 km carrera suave en sendero"],["Miércoles","Descanso"],["Jueves","5x2 min ritmo fuerte + 1 min trote suave en terreno variado"],["Viernes","5 km en sendero con desnivel moderado"],["Sábado","Descanso"],["Domingo","8 km carrera en sendero con terreno mixto"]],
        [["Lunes","Fuerza trail: 4x12 sentadillas + 4x10 zancadas + 6 cuestas de 30 seg"],["Martes","5 km carrera continua en sendero suave"],["Miércoles","Descanso"],["Jueves","6x2 min ritmo fuerte + 1 min recuperación en terreno irregular"],["Viernes","6 km en sendero con cuestas moderadas"],["Sábado","Descanso"],["Domingo","10 km carrera en sendero con desniveles variados"]],
        [["Lunes","Fuerza trail: 4x15 sentadillas + 4x12 zancadas + 8 cuestas de 40 seg"],["Martes","6 km carrera suave en sendero irregular"],["Miércoles","Descanso"],["Jueves","8x2 min fartlek en terreno variado: subida fuerte + bajada técnica"],["Viernes","7 km en sendero técnico con desniveles pronunciados"],["Sábado","Descanso"],["Domingo","12 km carrera en sendero con terreno técnico"]],
        [["Lunes","Fuerza trail: 5x12 sentadillas + 4x12 zancadas + 10 cuestas de 45 seg"],["Martes","7 km carrera continua en sendero irregular"],["Miércoles","Descanso"],["Jueves","6x3 min ritmo fuerte en subida + bajada técnica controlada"],["Viernes","8 km en sendero con desniveles y terreno técnico"],["Sábado","Descanso"],["Domingo","14 km carrera larga en sendero con terreno variado"]],
        [["Lunes","Fuerza trail: 5x15 sentadillas + 5x12 zancadas + 10 cuestas de 1 min"],["Martes","7 km carrera suave en sendero técnico (trabajo de bajada)"],["Miércoles","Descanso"],["Jueves","8x3 min fartlek en terreno montañoso: subidas y bajadas continuas"],["Viernes","8 km en sendero de montaña con desnivel acumulado alto"],["Sábado","Descanso"],["Domingo","16 km carrera larga en terreno de montaña variado"]],
        [["Lunes","Fuerza trail: 5x15 sentadillas + 5x12 zancadas + 12 cuestas de 1 min"],["Martes","8 km carrera suave en sendero técnico"],["Miércoles","Descanso"],["Jueves","10x2 min sprints en cuesta + bajada técnica controlada"],["Viernes","10 km en sendero accidentado con desniveles fuertes"],["Sábado","Descanso"],["Domingo","18 km carrera larga en terreno accidentado de montaña"]]
    ],
    "ejercicios":[
        [["Lunes","Pierna y core: 4x12 sentadillas + 4x10 zancadas por pierna + 3x30 seg plancha"],["Martes","Tren superior: 4x10 flexiones (apoyadas si hace falta) + 4x12 remo con mochila + 3x12 press hombro"],["Miércoles","Descanso"],["Jueves","Glúteos y core: 4x12 puente de glúteo + 3x12 peso muerto con mochila + 3x20 abdominales"],["Viernes","Movilidad y estabilidad: 20 min cadera/tobillo/espalda + 3x30 seg equilibrio por pierna"],["Sábado","Circuito full body: 4 rondas (12 sentadillas + 10 flexiones + 20 mountain climbers + 30 seg plancha)"],["Domingo","Descanso activo: caminar 30 min y estirar 10 min"]],
        [["Lunes","Pierna: 5x12 sentadillas + 4x12 zancadas + 3x15 elevación de gemelos"],["Martes","Tren superior: 4x12 flexiones + 4x10 fondos en silla + 4x12 remo con mochila"],["Miércoles","Descanso"],["Jueves","Core intenso: 4x35 seg plancha + 4x20 crunch + 4x12 elevaciones de piernas"],["Viernes","Movilidad + técnica: 25 min movilidad y activación"],["Sábado","Circuito metabólico: 5 rondas (12 burpees + 15 sentadillas + 12 zancadas + 30 seg plancha)"],["Domingo","Descanso"]],
        [["Lunes","Pierna y potencia: 4x10 sentadilla con salto + 4x10 zancada atrás + 4x12 sentadilla sumo"],["Martes","Tren superior: 5x10 flexiones + 4x12 remo + 4x12 press hombro"],["Miércoles","Descanso"],["Jueves","Core y estabilidad: 4x40 seg plancha + 4x20 bicicleta + 4x12 plancha lateral por lado"],["Viernes","Movilidad profunda: 25 min + trabajo de respiración"],["Sábado","Circuito full body: 5 rondas (10 burpees + 12 flexiones + 15 sentadillas + 20 escaladores)"],["Domingo","Descanso activo"]],
        [["Lunes","Pierna: 5x12 sentadilla búlgara + 4x12 peso muerto con mochila + 4x15 gemelos"],["Martes","Tren superior: 5x12 flexiones + 4x12 fondos + 4x12 remo"],["Miércoles","Descanso"],["Jueves","Core avanzado: 5x40 seg plancha + 4x20 crunch invertido + 4x15 elevación de piernas"],["Viernes","Movilidad y descarga: 20 min"],["Sábado","Test de circuito: 6 rondas (12 sentadillas + 10 flexiones + 12 zancadas + 30 seg plancha)"],["Domingo","Descanso"]]
    ],
    "sobrepeso":[
        [["Lunes","25 min caminata a ritmo cómodo"],["Martes","6x(1 min trote suave + 2 min caminando)"],["Miércoles","Descanso"],["Jueves","25 min caminata + movilidad 10 min"],["Viernes","8x(1 min trote suave + 2 min caminando)"],["Sábado","Descanso"],["Domingo","30 min caminata progresiva"]],
        [["Lunes","30 min caminata + fuerza básica (2x10 sentadilla a silla + 2x8 puente de glúteo)"],["Martes","8x(90 seg trote suave + 2 min caminando)"],["Miércoles","Descanso"],["Jueves","6x(2 min trote suave + 2 min caminando)"],["Viernes","30 min caminata con cambios de ritmo suaves"],["Sábado","Descanso"],["Domingo","7x(2 min trote suave + 90 seg caminando)"]],
        [["Lunes","30 min caminata + fuerza básica (3x10 sentadilla a silla + 2x20 seg plancha)"],["Martes","7x(3 min trote suave + 2 min caminando)"],["Miércoles","Descanso"],["Jueves","30 min caminata activa"],["Viernes","6x(4 min trote suave + 2 min caminando)"],["Sábado","Descanso"],["Domingo","35 min caminata/trote cómodo"]],
        [["Lunes","35 min caminata activa + movilidad 10 min"],["Martes","6x(5 min trote suave + 2 min caminando)"],["Miércoles","Descanso"],["Jueves","30 min caminata de recuperación"],["Viernes","5x(6 min trote suave + 2 min caminando)"],["Sábado","Descanso"],["Domingo","40 min caminata/trote continuo cómodo"]],
        [["Lunes","30 min caminata + fuerza (3x12 sentadilla a silla + 3x10 zancada asistida)"],["Martes","4x(8 min trote suave + 2 min caminando)"],["Miércoles","Descanso"],["Jueves","35 min caminata activa"],["Viernes","3x(10 min trote suave + 2 min caminando)"],["Sábado","Descanso"],["Domingo","45 min caminata/trote continuo cómodo"]],
        [["Lunes","35 min caminata + movilidad"],["Martes","2x(15 min trote suave + 3 min caminando)"],["Miércoles","Descanso"],["Jueves","30 min caminata de recuperación"],["Viernes","30 min trote continuo muy cómodo"],["Sábado","Descanso"],["Domingo","50 min caminata/trote cómodo"]]
    ]
};