// planes.js - Datos de los planes de entrenamiento
const planes = {
    "30min":[
        [["Lunes","20 min caminata rápida + 3x10 sentadillas"],["Martes","5x1 min trote suave + 2 min caminando"],["Miércoles","Descanso"],["Jueves","6x1 min trote + 1.5 min caminando"],["Viernes","15 min caminata rápida con cambios de ritmo"],["Sábado","Descanso"],["Domingo","4x1.5 min trote + 2 min caminando"]],
        [["Lunes","20 min caminata rápida + 3x12 sentadillas + 10 zancadas"],["Martes","5x2 min trote suave + 1.5 min caminando"],["Miércoles","Descanso"],["Jueves","6x2 min trote + 1 min caminando"],["Viernes","18 min alternando 2 min trote + 1 min caminar"],["Sábado","Descanso"],["Domingo","4x2.5 min trote + 1.5 min caminando"]],
        [["Lunes","15 min caminata + 3x15 sentadillas + 12 zancadas"],["Martes","4x3 min trote + 1 min caminando"],["Miércoles","Descanso"],["Jueves","6x2 min trote con 30 seg más rápido al final + 1 min caminar"],["Viernes","10 min trote continuo suave"],["Sábado","Descanso"],["Domingo","3x5 min trote + 2 min caminando"]],
        [["Lunes","15 min caminata rápida + 4x12 sentadillas + 3x10 zancadas"],["Martes","3x5 min trote + 1 min caminando"],["Miércoles","Descanso"],["Jueves","5x3 min trote con último min más rápido + 1 min caminar"],["Viernes","12 min trote continuo suave"],["Sábado","Descanso"],["Domingo","2x8 min trote + 2 min caminando"]],
        [["Lunes","10 min caminata + 4x15 sentadillas + 3x12 zancadas"],["Martes","15 min trote continuo suave"],["Miércoles","Descanso"],["Jueves","4x3 min ritmo medio + 1 min trote suave"],["Viernes","12 min trote + 3 min más rápido"],["Sábado","Descanso"],["Domingo","18 min trote continuo a ritmo cómodo"]],
        [["Lunes","10 min caminata + 4x15 sentadillas + 4x12 zancadas"],["Martes","18 min trote continuo suave"],["Miércoles","Descanso"],["Jueves","5x3 min ritmo medio + 1 min trote suave"],["Viernes","15 min trote + 3 min progresivo"],["Sábado","Descanso"],["Domingo","22 min trote continuo a ritmo cómodo"]],
        [["Lunes","10 min caminata + 4x15 sentadillas + 4x12 zancadas + 30 seg plancha"],["Martes","22 min trote continuo suave"],["Miércoles","Descanso"],["Jueves","4x4 min ritmo medio + 1 min trote suave"],["Viernes","18 min trote + 4 min progresivo"],["Sábado","Descanso"],["Domingo","25 min trote continuo a ritmo cómodo"]],
        [["Lunes","10 min caminata + 4x15 sentadillas + 4x12 zancadas + 45 seg plancha"],["Martes","25 min trote continuo suave"],["Miércoles","Descanso"],["Jueves","3x5 min ritmo medio + 1 min trote suave"],["Viernes","20 min trote + 5 min progresivo"],["Sábado","Descanso"],["Domingo","30 min trote continuo"]]
    ],
    "5k":[
        [["Lunes","Fuerza básica: 3x12 sentadillas + 10 zancadas + 20 seg plancha"],["Martes","2 km trote suave alternando con caminata"],["Miércoles","Descanso"],["Jueves","6x1 min trote + 1.5 min caminando"],["Viernes","2 km trote suave continuo"],["Sábado","Descanso"],["Domingo","2.5 km trote/caminata a ritmo cómodo"]],
        [["Lunes","Fuerza: 3x15 sentadillas + 12 zancadas + 30 seg plancha"],["Martes","2.5 km trote suave continuo"],["Miércoles","Descanso"],["Jueves","5x2 min trote + 1 min caminando"],["Viernes","2.5 km trote con últimos 500m más rápido"],["Sábado","Descanso"],["Domingo","3 km trote suave continuo"]],
        [["Lunes","Fuerza: 4x12 sentadillas + 3x10 zancadas + 30 seg plancha + skipping"],["Martes","3 km carrera suave continua"],["Miércoles","Descanso"],["Jueves","6x200m ritmo rápido + 200m trote suave"],["Viernes","3 km con último km a ritmo medio"],["Sábado","Descanso"],["Domingo","4 km carrera suave"]],
        [["Lunes","Fuerza: 4x15 sentadillas + 3x12 zancadas + 40 seg plancha + skipping"],["Martes","3.5 km carrera suave continua"],["Miércoles","Descanso"],["Jueves","5x400m ritmo fuerte + 400m trote suave"],["Viernes","3 km tempo a ritmo medio constante"],["Sábado","Descanso"],["Domingo","5 km carrera suave"]],
        [["Lunes","Fuerza: 4x15 sentadillas + 4x12 zancadas + 45 seg plancha"],["Martes","4 km carrera suave continua"],["Miércoles","Descanso"],["Jueves","4x600m a ritmo 5K + 400m trote suave"],["Viernes","4 km con 2 km centrales a ritmo 5K"],["Sábado","Descanso"],["Domingo","6 km carrera suave"]],
        [["Lunes","Fuerza: 4x15 sentadillas + 4x12 zancadas + 45 seg plancha + técnica carrera"],["Martes","4 km carrera suave"],["Miércoles","Descanso"],["Jueves","3x1000m a ritmo 5K + 500m trote suave"],["Viernes","5 km con 3 km centrales a ritmo 5K"],["Sábado","Descanso"],["Domingo","7 km carrera suave"]],
        [["Lunes","Fuerza ligera: 3x12 sentadillas + 3x10 zancadas + 30 seg plancha"],["Martes","4 km carrera suave"],["Miércoles","Descanso"],["Jueves","6x400m a ritmo 5K + 200m trote"],["Viernes","3 km suave + 2 km progresivo hasta ritmo 5K"],["Sábado","Descanso"],["Domingo","5 km simulacro a ritmo objetivo"]],
        [["Lunes","Activación: 15 min trote muy suave + movilidad articular"],["Martes","3 km carrera suave"],["Miércoles","Descanso"],["Jueves","4x200m ritmo rápido + trote suave (activación)"],["Viernes","2 km trote muy suave + estiramientos"],["Sábado","Descanso"],["Domingo","CARRERA 5K – ¡A darlo todo!"]]
    ],
    "fartlek":[
        [["Lunes","2 km corriendo + 1 km fartlek suave"],["Martes","2 km corriendo + 1 km fartlek suave"],["Miércoles","Descanso"],["Jueves","2 km corriendo + 1 km fartlek suave"],["Viernes","2 km corriendo + 1 km fartlek suave"],["Sábado","Descanso"],["Domingo","2 km corriendo + 1 km fartlek suave"]],
        [["Lunes","3 km corriendo + 1 km fartlek intercalando"],["Martes","3 km corriendo + 1 km fartlek intercalando"],["Miércoles","Descanso"],["Jueves","3 km corriendo + 1 km fartlek intercalando"],["Viernes","3 km corriendo + 1 km fartlek intercalando"],["Sábado","Descanso"],["Domingo","3 km corriendo + 1 km fartlek intercalando"]],
        [["Lunes","4 km con cambios de ritmo frecuentes"],["Martes","4 km con cambios de ritmo frecuentes"],["Miércoles","Descanso"],["Jueves","4 km con cambios de ritmo frecuentes"],["Viernes","4 km con cambios de ritmo frecuentes"],["Sábado","Descanso"],["Domingo","4 km con cambios de ritmo frecuentes"]],
        [["Lunes","5 km con 3 segmentos fartlek rápidos"],["Martes","5 km con 3 segmentos fartlek rápidos"],["Miércoles","Descanso"],["Jueves","5 km con 3 segmentos fartlek rápidos"],["Viernes","5 km con 3 segmentos fartlek rápidos"],["Sábado","Descanso"],["Domingo","5 km con 3 segmentos fartlek rápidos"]],
        [["Lunes","5 km continuos con variación de ritmo"],["Martes","5 km continuos con variación de ritmo"],["Miércoles","Descanso"],["Jueves","5 km continuos con variación de ritmo"],["Viernes","5 km continuos con variación de ritmo"],["Sábado","Descanso"],["Domingo","5 km continuos con variación de ritmo"]],
        [["Lunes","6 km con 4 cambios de ritmo intensos"],["Martes","6 km con 4 cambios de ritmo intensos"],["Miércoles","Descanso"],["Jueves","6 km con 4 cambios de ritmo intensos"],["Viernes","6 km con 4 cambios de ritmo intensos"],["Sábado","Descanso"],["Domingo","6 km con 4 cambios de ritmo intensos"]]
    ],
    "hiit":[
        [["Lunes","Fuerza explosiva: 3 rondas de 20s sentadilla con salto + 40s descanso x5"],["Martes","Cardio HIIT: 3 rondas de 20s sprint + 40s caminar x5"],["Miércoles","Descanso"],["Jueves","Circuito: 3 rondas (20s burpees + 20s skipping + 20s sentadillas) 40s descanso"],["Viernes","Core HIIT: 3 rondas de 20s mountain climbers + 20s plancha + 40s descanso"],["Sábado","Descanso"],["Domingo","HIIT largo: 4x1 min trote rápido + 1 min caminando"]],
        [["Lunes","Fuerza explosiva: 3 rondas de 20s salto zancada + 20s sentadilla salto + 40s desc x4"],["Martes","Cardio HIIT: 3 rondas de 20s sprint cuesta + 40s bajar caminando x5"],["Miércoles","Descanso"],["Jueves","Circuito: 3 rondas (20s burpees + 20s jumping jacks + 20s plancha) 40s desc"],["Viernes","Core HIIT: 3 rondas (20s mountain climbers + 20s plancha lateral + 20s bicicleta) 40s desc"],["Sábado","Descanso"],["Domingo","HIIT largo: 5x1 min trote rápido + 1 min caminando"]],
        [["Lunes","Fuerza explosiva: 3 rondas de 30s sentadilla salto + 30s zancada salto + 30s desc x4"],["Martes","Cardio HIIT: 3 rondas de 30s sprint + 30s trote suave x6"],["Miércoles","Descanso"],["Jueves","Circuito: 3 rondas (30s burpees + 30s skipping + 30s sentadillas + 30s plancha) 30s desc"],["Viernes","Core + plio: 3 rondas (30s mountain climbers + 30s saltos tijera + 30s plancha dinámica) 30s desc"],["Sábado","Descanso"],["Domingo","HIIT largo: 5x90 seg ritmo fuerte + 1 min caminando"]],
        [["Lunes","Fuerza explosiva: 3 rondas (30s sentadilla salto + 30s burpees + 30s zancada salto) 30s desc"],["Martes","Cardio HIIT: 4 rondas de 30s sprint + 30s trote suave x6"],["Miércoles","Descanso"],["Jueves","Circuito: 3 rondas (30s burpees + 30s jumping jacks + 30s sentadillas + 30s skipping + 30s plancha) 30s desc"],["Viernes","Core + plio: 3 rondas (30s mountain climbers + 30s rodillas al pecho + 30s salto estrella) 30s desc"],["Sábado","Descanso"],["Domingo","HIIT largo: 6x90 seg ritmo fuerte + 45 seg caminando"]],
        [["Lunes","Fuerza explosiva: 3 rondas (40s sentadilla salto + 40s burpees + 40s zancada salto) 20s desc"],["Martes","Tabata cardio: 4 rondas de 20s sprint máximo + 10s descanso x8"],["Miércoles","Descanso"],["Jueves","Circuito: 4 rondas (40s burpees + 40s skipping + 40s sentadilla salto + 40s plancha) 20s desc"],["Viernes","Core + plio: 4 rondas (40s mountain climbers + 40s plancha dinámica + 40s saltos laterales) 20s desc"],["Sábado","Descanso"],["Domingo","HIIT largo: 6x2 min ritmo fuerte + 45 seg trote suave"]],
        [["Lunes","Fuerza explosiva: 4 rondas (40s sentadilla salto + 40s burpees + 40s zancada explosiva) 20s desc"],["Martes","Tabata cardio: 4 rondas de 20s sprint máximo + 10s desc x8 (2 min pausa entre rondas)"],["Miércoles","Descanso"],["Jueves","Circuito: 4 rondas (40s burpees + 40s jumping jacks + 40s sentadilla salto + 40s skipping + 40s plancha) 20s desc"],["Viernes","Core intenso: 4 rondas (40s mountain climbers + 40s V-ups + 40s plancha lateral dinámica) 20s desc"],["Sábado","Descanso"],["Domingo","HIIT largo: 8x2 min ritmo fuerte + 30 seg trote suave"]],
        [["Lunes","Fuerza explosiva: 4 rondas (45s sentadilla salto + 45s burpees + 45s zancada salto) 15s desc"],["Martes","Tabata mixto: 4 rondas (20s burpee + 10s desc + 20s sprint + 10s desc) x4"],["Miércoles","Descanso"],["Jueves","Circuito: 4 rondas (45s burpees + 45s skipping + 45s sentadilla salto + 45s mountain climbers + 45s plancha) 15s desc"],["Viernes","Core + plio: 4 rondas (45s mountain climbers + 45s saltos estrella + 45s plancha dinámica + 45s tijeras) 15s desc"],["Sábado","Descanso"],["Domingo","HIIT largo: 8x2 min ritmo fuerte + 20 seg recuperación activa"]],
        [["Lunes","Fuerza explosiva: 4 rondas (45s sentadilla salto + 45s burpees + 45s zancada explosiva + 45s flexiones) 15s desc"],["Martes","Tabata final: 5 rondas (20s sprint máximo + 10s desc) x8"],["Miércoles","Descanso"],["Jueves","Circuito completo: 4 rondas (45s burpees + 45s skipping + 45s sentadilla salto + 45s mountain climbers + 45s plancha + 45s jumping jacks) 15s desc"],["Viernes","Core final: 4 rondas (45s mountain climbers + 45s V-ups + 45s plancha dinámica + 45s rodillas al pecho) 15s desc"],["Sábado","Descanso"],["Domingo","HIIT test: 10x1 min sprint máximo + 30 seg descanso"]]
    ],
    "trail":[
        [["Lunes","Fuerza básica: 3x10 sentadillas + 3x10 zancadas + 20 min caminata en sendero"],["Martes","3 km trote suave en sendero llano"],["Miércoles","Descanso"],["Jueves","20 min alternando 2 min trote + 1 min caminar en sendero"],["Viernes","30 min caminata en sendero con desnivel suave"],["Sábado","Descanso"],["Domingo","5 km caminata/trote en sendero natural"]],
        [["Lunes","Fuerza: 3x12 sentadillas + 3x10 zancadas + 10 min escalones"],["Martes","4 km trote suave en sendero llano"],["Miércoles","Descanso"],["Jueves","25 min alternando 3 min trote + 1 min caminar en sendero"],["Viernes","35 min trote suave en sendero con cuestas cortas"],["Sábado","Descanso"],["Domingo","6 km trote suave en sendero natural"]],
        [["Lunes","Fuerza trail: 4x10 sentadillas + 4x10 zancadas + 15 min subida/bajada escalones"],["Martes","5 km carrera suave en sendero"],["Miércoles","Descanso"],["Jueves","5x2 min ritmo fuerte + 1 min trote suave en terreno variado"],["Viernes","5 km en sendero con desnivel moderado"],["Sábado","Descanso"],["Domingo","8 km carrera en sendero con terreno mixto"]],
        [["Lunes","Fuerza trail: 4x12 sentadillas + 4x10 zancadas + 6 cuestas de 30 seg"],["Martes","5 km carrera continua en sendero suave"],["Miércoles","Descanso"],["Jueves","6x2 min ritmo fuerte + 1 min recuperación en terreno irregular"],["Viernes","6 km en sendero con cuestas moderadas"],["Sábado","Descanso"],["Domingo","10 km carrera en sendero con desniveles variados"]],
        [["Lunes","Fuerza trail: 4x15 sentadillas + 4x12 zancadas + 8 cuestas de 40 seg"],["Martes","6 km carrera suave en sendero irregular"],["Miércoles","Descanso"],["Jueves","8x2 min fartlek en terreno variado: subida fuerte + bajada técnica"],["Viernes","7 km en sendero técnico con desniveles pronunciados"],["Sábado","Descanso"],["Domingo","12 km carrera en sendero con terreno técnico"]],
        [["Lunes","Fuerza trail: 5x12 sentadillas + 4x12 zancadas + 10 cuestas de 45 seg"],["Martes","7 km carrera continua en sendero irregular"],["Miércoles","Descanso"],["Jueves","6x3 min ritmo fuerte en subida + bajada técnica controlada"],["Viernes","8 km en sendero con desniveles y terreno técnico"],["Sábado","Descanso"],["Domingo","14 km carrera larga en sendero con terreno variado"]],
        [["Lunes","Fuerza trail: 5x15 sentadillas + 5x12 zancadas + 10 cuestas de 1 min"],["Martes","7 km carrera suave en sendero técnico (trabajo de bajada)"],["Miércoles","Descanso"],["Jueves","8x3 min fartlek en terreno montañoso: subidas y bajadas continuas"],["Viernes","8 km en sendero de montaña con desnivel acumulado alto"],["Sábado","Descanso"],["Domingo","16 km carrera larga en terreno de montaña variado"]],
        [["Lunes","Fuerza trail: 5x15 sentadillas + 5x12 zancadas + 12 cuestas de 1 min"],["Martes","8 km carrera suave en sendero técnico"],["Miércoles","Descanso"],["Jueves","10x2 min sprints en cuesta + bajada técnica controlada"],["Viernes","10 km en sendero accidentado con desniveles fuertes"],["Sábado","Descanso"],["Domingo","18 km carrera larga en terreno accidentado de montaña"]]
    ],
    "sobrepeso":[
        [["Lunes","10 min caminando + 1 min corriendo"],["Martes","10 min caminando + 1 min corriendo"],["Miércoles","Descanso"],["Jueves","10 min caminando + 1 min corriendo"],["Viernes","10 min caminando + 1 min corriendo"],["Sábado","Descanso"],["Domingo","10 min caminando + 1 min corriendo"]],
        [["Lunes","15 min caminando + 2 min corriendo"],["Martes","15 min caminando + 2 min corriendo"],["Miércoles","Descanso"],["Jueves","15 min caminando + 2 min corriendo"],["Viernes","15 min caminando + 2 min corriendo"],["Sábado","Descanso"],["Domingo","15 min caminando + 2 min corriendo"]],
        [["Lunes","20 min caminando + 3 min corriendo"],["Martes","20 min caminando + 3 min corriendo"],["Miércoles","Descanso"],["Jueves","20 min caminando + 3 min corriendo"],["Viernes","20 min caminando + 3 min corriendo"],["Sábado","Descanso"],["Domingo","20 min caminando + 3 min corriendo"]],
        [["Lunes","25 min caminando + 4 min corriendo"],["Martes","25 min caminando + 4 min corriendo"],["Miércoles","Descanso"],["Jueves","25 min caminando + 4 min corriendo"],["Viernes","25 min caminando + 4 min corriendo"],["Sábado","Descanso"],["Domingo","25 min caminando + 4 min corriendo"]],
        [["Lunes","30 min caminando + 5 min corriendo"],["Martes","30 min caminando + 5 min corriendo"],["Miércoles","Descanso"],["Jueves","30 min caminando + 5 min corriendo"],["Viernes","30 min caminando + 5 min corriendo"],["Sábado","Descanso"],["Domingo","30 min caminando + 5 min corriendo"]],
        [["Lunes","35 min caminando + 6 min corriendo"],["Martes","35 min caminando + 6 min corriendo"],["Miércoles","Descanso"],["Jueves","35 min caminando + 6 min corriendo"],["Viernes","35 min caminando + 6 min corriendo"],["Sábado","Descanso"],["Domingo","35 min caminando + 6 min corriendo"]]
    ]
};